import swaggerJsdoc from 'swagger-jsdoc';
import { env } from './env.js';

/**
 * Swagger/OpenAPI Configuration
 *
 * Generates OpenAPI 3.0.3 specification from JSDoc comments.
 * Documentation is automatically generated by scanning route files.
 */

const swaggerDefinition = {
  openapi: '3.0.3',
  info: {
    title: env.API_TITLE || 'Tasbeeh API',
    version: env.API_VERSION || '1.0.0',
    description: `Comprehensive API documentation for the Tasbeeh application.`,
  },
  servers: [
    {
      url: env.API_BASE_URL || 'http://localhost:3000',
      description: 'Development server',
    },
    {
      url: 'https://staging-api.tasbeeh.com',
      description: 'Staging server',
    },
    {
      url: 'https://api.tasbeeh.com',
      description: 'Production server',
    },
  ],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        description: 'Enter your JWT token obtained from login/register endpoint',
      },
    },
    responses: {
      UnauthorizedError: {
        description: 'Authentication token is missing or invalid',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                success: {
                  type: 'boolean',
                  example: false,
                },
                message: {
                  type: 'string',
                  example: 'Authentication required',
                },
                errorCode: {
                  type: 'string',
                  example: 'UNAUTHORIZED',
                },
              },
            },
          },
        },
      },
      ForbiddenError: {
        description: 'User does not have permission to access this resource',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                success: {
                  type: 'boolean',
                  example: false,
                },
                message: {
                  type: 'string',
                  example: 'Insufficient permissions',
                },
                errorCode: {
                  type: 'string',
                  example: 'FORBIDDEN',
                },
              },
            },
          },
        },
      },
      NotFoundError: {
        description: 'The requested resource was not found',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                success: {
                  type: 'boolean',
                  example: false,
                },
                message: {
                  type: 'string',
                  example: 'Resource not found',
                },
                errorCode: {
                  type: 'string',
                  example: 'NOT_FOUND',
                },
              },
            },
          },
        },
      },
      ValidationError: {
        description: 'Request validation failed',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                success: {
                  type: 'boolean',
                  example: false,
                },
                message: {
                  type: 'string',
                  example: 'Validation failed',
                },
                errorCode: {
                  type: 'string',
                  example: 'VALIDATION_ERROR',
                },
                errors: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      field: {
                        type: 'string',
                        example: 'email',
                      },
                      message: {
                        type: 'string',
                        example: 'Invalid email format',
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      ConflictError: {
        description: 'The request conflicts with existing data',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                success: {
                  type: 'boolean',
                  example: false,
                },
                message: {
                  type: 'string',
                  example: 'Resource already exists',
                },
                errorCode: {
                  type: 'string',
                  example: 'CONFLICT',
                },
              },
            },
          },
        },
      },
      ServerError: {
        description: 'Internal server error',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                success: {
                  type: 'boolean',
                  example: false,
                },
                message: {
                  type: 'string',
                  example: 'An unexpected error occurred',
                },
                errorCode: {
                  type: 'string',
                  example: 'INTERNAL_SERVER_ERROR',
                },
              },
            },
          },
        },
      },
    },
  },
  tags: [
    {
      name: 'Authentication',
      description: 'User authentication and authorization endpoints',
    },
    {
      name: 'Devices',
      description: 'Device management and synchronization endpoints',
    },
    {
      name: 'Health',
      description: 'API health check endpoints',
    },
  ],
};

/**
 * Swagger JSDoc configuration options
 */
const options: swaggerJsdoc.Options = {
  definition: swaggerDefinition,
  // Paths to files containing OpenAPI definitions in JSDoc comments
  apis: [
    './src/modules/**/*.routes.ts',
    './src/routes/**/*.ts',
    './src/config/swagger.schemas.ts',
  ],
};

/**
 * Generate OpenAPI specification
 */
export const swaggerSpec = swaggerJsdoc(options);

/**
 * Swagger UI options
 */
export const swaggerUiOptions = {
  customCss: `
    .swagger-ui .topbar { display: none }
    .swagger-ui .info .title { color: #2c3e50; }
    .swagger-ui .opblock-tag { font-size: 18px; font-weight: bold; }
  `,
  customSiteTitle: 'Tasbeeh API Documentation',
  swaggerOptions: {
    persistAuthorization: true, // Remember JWT token in browser
    displayRequestDuration: true, // Show request duration
    docExpansion: 'none', // Collapse all sections by default
    filter: true, // Enable search/filter
    tryItOutEnabled: true, // Enable "Try it out" by default
    defaultModelsExpandDepth: 3, // How deep to expand models
    defaultModelExpandDepth: 3,
    displayOperationId: false,
    syntaxHighlight: {
      activate: true,
      theme: 'agate',
    },
  },
};
